name: use reusable workflow
on:
    workflow_dispatch:

jobs:
    call-reusable-workflow-in-local-repo:
        uses: ClemtZal/sfeir-school-github-actions-template-czi/.github/workflows/ex4.yaml@main
        with:
            node_version: "24"
