name: cache
on:
    workflow_dispatch:

jobs:
    run-npm-install:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6
            - name: setup node
              id: node-setup
              uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"
            - name: Cache node_modules
              uses: actions/cache@v4
              id: node_modules_restore
              env:
                  NODE_VERSION: ${{ steps.node-setup.outputs.node-version }}
              with:
                  key: cache-node-${{ env.NODE_VERSION }}
                  path: |
                      ./node_modules
            - name: run install
              shell: bash
              run: |
                  npm install
            - name: Cache node_modules
              uses: actions/cache@v4
              id: node_modules_cache
              env:
                  NODE_VERSION: ${{ steps.node-setup.outputs.node-version }}
              with:
                  key: cache-node-$NODE_VERSION
                  path: |
                      ./node_modules

    run-npm-test:
        runs-on: ubuntu-latest
        needs: run-npm-install
        steps:
            - name: checkout
              uses: actions/checkout@v6
            - name: setup node
              id: node-setup
              uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"
            - name: Cache node_modules
              uses: actions/cache@v4
              id: node_modules_restore
              env:
                  NODE_VERSION: ${{ steps.node-setup.outputs.node-version }}
              with:
                  key: cache-node-${{ env.NODE_VERSION }}
                  path: |
                      ./node_modules
            - name: run test
              shell: bash
              run: |
                  npm test
