name: build docker
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    run-npm-install:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6
            - name: setup node
              id: setup-node
              uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"
            - name: Cache node_modules
              uses: actions/cache@v4
              id: node_modules_restore
              env:
                  NODE_VERSION: ${{ steps.setup-node.outputs.node-version }}
              with:
                  key: cache-node-${{ env.NODE_VERSION }}
                  path: |
                      ./node_modules
            - name: run install
              shell: bash
              run: |
                  npm install
                  npm test
            - name: Cache node_modules
              uses: actions/cache@v4
              id: node_modules_cache
              env:
                  NODE_VERSION: ${{ steps.setup-node.outputs.node-version }}
              with:
                  key: cache-node-$NODE_VERSION
                  path: |
                      ./node_modules
    docker-build:
        runs-on: ubuntu-latest
        needs: run-npm-install
        steps:
            - name: checkout
              uses: actions/checkout@v6
            - name: docker build
              if: ${{ github.ref == 'refs/heads/main' }}
              run: docker build -t ${{ github.sha }} .
