name: npm test matrix
on:
    workflow_dispatch:

jobs:
    run-npm-install:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node_version:
                    - 20
                    - "lts"
                runner-os: [ubuntu-latest, ubuntu-22.04]
                include:
                    - node_version: 18
                      runner-os: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6
            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"
            - name: run install
              shell: bash
              run: |
                  npm install
                  npm test
